title: Rahul Pandey
description: "Startups, programming, design, and anything in between, and everything not in between."

url: http://rpdemo.github.io/
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: rahulpandeyc
   twitter: rahulpandeyc
   facebook: rahulpandey.net
   email: hi@rahulpandey.net

google_analytics: ""
